query Game($slug: String!, $locale: String!) {
  game(slug: $slug) {
    id
    slug
    name
    localizedDescription(locale: $locale) {
      text
      language
      source
    }
    released
    rating
    ratingsCount
    metacritic
    playtime
    ageRating
    gameModes
    website
    cover {
      url
    }
    screenshots {
      url
      width
      height
    }
    platformFamilies
    platforms {
      id
      slug
      name
    }
    genres {
      id
      slug
      name
    }
    developers {
      id
      slug
      name
    }
    publishers {
      id
      slug
      name
    }
    stores {
      store
      url
    }
  }
}
